name: Helm Cleanup

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '!rakbank-terraform/**'

jobs:
  helm-uninstall:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name my-cluster --region ap-south-1

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Uninstall Helm Release
      run: |
        helm uninstall rakbankdemoapp

