name: terraform infra creation
on: 
  workflow_dispatch:  # You can trigger this workflow manually or on other events (push, pull_request)
  push:
    branches:
      - main
    paths:
      - 'rakbank-terraform/**'
jobs:
  infra-creation:
    name: terraform infra creation
    runs-on: ubuntu-latest  # You can choose a different runner (e.g., ubuntu-18.04) if needed
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Downloads your code from the repository

      - name: Setup AWS Credentials
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            echo "Setting up AWS credentials"
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Terraform Init
        id: fmt
        run: cd ./rakbank-terraform && terraform init


      - name: Terraform fmt
        id: init
        run: cd ./rakbank-terraform &&  terraform fmt --check
        

      - name: Terraform Validate
        id: validate
        run: cd ./rakbank-terraform &&  terraform validate -no-color
        

      - name: Terraform Plan
        id: plan
        run: |
          cd ./rakbank-terraform 
          terraform plan --out ./tfplan -no-color
          terraform show -json ./tfplan > ./tfplan.json
       

      - name: Terraform Apply
        id: apply
        if: contains(github.event.head_commit.message, 'terraform apply')
        run: cd ./rakbank-terraform &&  terraform apply -auto-approve

      - name: Set apply status
        if: ${{ success() }}
        run: echo "::set-output name=apply::success"



      - name: Terraform Destroy
        id: destroy
        if: contains(github.event.head_commit.message, 'terraform destroy')
        run: cd ./rakbank-terraform &&  terraform destroy -auto-approve

  buildStage:
    needs: [infra-creation]
    if: ${{ needs.infra-creation.outputs.apply == 'success' }}
    uses:  ./.github/workflows/build.yaml
      
