name: Infra Create and App Deployment
on: 
  workflow_dispatch:  # You can trigger this workflow manually or on other events (push, pull_request)
  push:
    branches:
      - main
    paths:
      - 'rakbank-terraform/**'
jobs:
  infra-creation:
    name: terraform infra creation
    outputs:
      output1: ${{ steps.set-status.outputs.apply_status }}
    runs-on: ubuntu-latest  # You can choose a different runner (e.g., ubuntu-18.04) if needed
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Downloads your code from the repository

      - name: Setup AWS Credentials
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            echo "Setting up AWS credentials"
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Terraform Init
        id: fmt
        run: cd ./rakbank-terraform && terraform init


      - name: Terraform fmt
        id: init
        run: cd ./rakbank-terraform &&  terraform fmt --check
        

      - name: Terraform Validate
        id: validate
        run: cd ./rakbank-terraform &&  terraform validate -no-color
        

      - name: Terraform Plan
        id: plan
        run: |
          cd ./rakbank-terraform 
          terraform plan --out ./tfplan -no-color
          terraform show -json ./tfplan > ./tfplan.json
       

      - name: Terraform Apply
        id: apply
        if: contains(github.event.head_commit.message, 'terraform apply')
        run: cd ./rakbank-terraform &&  terraform apply -auto-approve

      - name: Set apply status
        id: set-status
        if: success()
        run: echo "apply_status=true" >> $GITHUB_OUTPUT
      
     

      - name: Terraform Destroy
        id: destroy
        if: contains(github.event.head_commit.message, 'terraform destroy')
        run: cd ./rakbank-terraform &&  terraform destroy -auto-approve

  
  sonar:
    runs-on: ubuntu-latest
    needs: infra-creation
    if: needs.infra-creation.outputs.output1 == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Verify Java and Maven Version
      run: |
        java -version
        mvn -version

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven (Sonar Preparation)
      run: mvn clean compile
      working-directory: demo

    - name: Run SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar -Dsonar.projectKey=rakbankdubai_rakbank-assignment -Dsonar.organization=rakbankdubai -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      working-directory: demo

    # - name: Check Quality Gate
    #   id: check_quality_gate
    #   run: |
    #     echo "Checking Quality Gate status..."
    #     status=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=rakbankdubai_rakbank-assignment" | jq -r .projectStatus.status)
    #     echo "Quality Gate status: $status"
    #     if [ "$status" != "OK" ]; then
    #       echo "Quality Gate failed"
    #       echo "::set-output name=quality_gate_status::failed"
    #       exit 1
    #     else
    #       echo "Quality Gate passed"
    #       echo "::set-output name=quality_gate_status::passed"
    #     fi
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: sonar
    runs-on: ubuntu-latest
    #if: needs.sonar.outputs.quality_gate_status == 'passed'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: |
        mvn clean install
        mvn -B package
      working-directory: demo

    - name: Verify .jar file exists
      run: ls -l demo/target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Setup AWS Credentials
    #   env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: |
    #       echo "Setting up AWS credentials"
    #       aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    #       aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-south-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 211125715340.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: 211125715340.dkr.ecr.ap-south-1.amazonaws.com
        ECR_REPOSITORY: rakbankdemoregistry
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Building Docker image..."
        # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # echo "Pushing Docker image..."
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        # echo "getting the IMAGE_DIGEST"
        # IMAGE_DIGEST=$(aws ecr describe-images --repository-name $ECR_REPOSITORY --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageDigest' --output text)
        # echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >> $GITHUB_ENV
        
    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name my-cluster --region ap-south-1

    - name: Create or Update Kubernetes Deployment
      run: |
        kubectl create deployment rakbankdemoapp --image=211125715340.dkr.ecr.ap-south-1.amazonaws.com/rakbankdemoregistry@$IMAGE_DIGEST --dry-run=client -o yaml | kubectl apply -f -
        kubectl rollout status deployment/rakbankdemoapp
      
